
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemapi_ package provides tools for auto-generation of Python
APIs rom JSONSchema_ specifications. It makes use of the traitlets_ package
to generate object hierarchies that are equivalent to a given JSONSchema
specification.

See more information in the README_.

.. _README: https://github.com/altair-viz/schemapi/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _traitlets: https://traitlets.readthedocs.io
.. _schemapi: https://github.com/altair-viz/schemapi
"""
short_version = '0.4.0'
version = '0.4.0'
full_version = '0.4.0.dev0+0bd2321'
git_revision = '0bd232102c0e0052e741024c1f3acb36213ea212'
release = False
if not release:
    version = full_version
