
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemapi_ package provides tools for auto-generation of Python
APIs from JSONSchema_ specifications.

See more information in the README_.

.. _README: https://github.com/altair-viz/schemapi/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _schemapi: https://github.com/altair-viz/schemapi
"""
short_version = '0.4.0'
version = '0.4.0'
full_version = '0.4.0.dev0+8d60841'
git_revision = '8d60841a1599e7767876fb08df2c3d28eaa6978a'
release = False
if not release:
    version = full_version
