
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemapi_ package provides tools for auto-generation of Python
APIs rom JSONSchema_ specifications. It makes use of the traitlets_ package
to generate object hierarchies that are equivalent to a given JSONSchema
specification.

See more information in the README_.

.. _README: https://github.com/altair-viz/schemapi/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _traitlets: https://traitlets.readthedocs.io
.. _schemapi: https://github.com/altair-viz/schemapi
"""
short_version = '0.2.0'
version = '0.2.0'
full_version = '0.2.0'
git_revision = '28781a602160a539056e2a25a3e25185765e6773'
release = True
if not release:
    version = full_version
