
# This file is automatically generated by the setup.py script
long_description = """
Altair-Parser
=============
Altair-Parser provides tools for auto-generation of traitlets object
hierarchies generated from JSONSchema definitions.
See more information in the README_.

.. _README: https://github.com/altair-viz/altair_parser/blob/master/README.md
"""
short_version = '0.2.0'
version = '0.2.0'
full_version = '0.2.0.dev0+89423fa'
git_revision = '89423fab0f2f1cdeacf8f172c0cbbd35786f3dd7'
release = False
if not release:
    version = full_version
