
# This file is automatically generated by the setup.py script
long_description = """
Altair-Parser
=============
Altair-Parser provides tools for auto-generation of traitlets object
hierarchies generated from JSONSchema definitions.
See more information in the README_.

.. _README: https://github.com/altair-viz/altair_parser/blob/master/README.md
"""
short_version = '0.2.0'
version = '0.2.0'
full_version = '0.2.0.dev0+0ca6a15'
git_revision = '0ca6a152a48ef47d4f0c794e6a5b234a5ae0ae58'
release = False
if not release:
    version = full_version
