
# This file is automatically generated by the setup.py script
long_description = """
Altair-Parser
=============
Altair-Parser provides tools for auto-generation of traitlets object
hierarchies generated from JSONSchema definitions.
See more information in the README_.

.. _README: https://github.com/altair-viz/altair_parser/blob/master/README.md
"""
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0'
git_revision = '30d22413f6cc67c5276ce8e008c5add0d673122a'
release = True
if not release:
    version = full_version
