
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The jsonschema_apigen_ package provides tools for auto-generation of Python
APIs rom JSONSchema_ specifications. It makes use of the traitlets_ package
to generate object hierarchies that are equivalent to a given JSONSchema
specification.

See more information in the README_.

.. _README: https://github.com/altair-viz/jsonschema_apigen/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _traitlets: https://traitlets.readthedocs.io
.. _jsonschema_apigen: https://github.com/altair-viz/jsonschema_apigen
"""
short_version = '0.2.0'
version = '0.2.0'
full_version = '0.2.0.dev0+a48e02e'
git_revision = 'a48e02efc0397acbab18fe123d2a28d25af9d486'
release = False
if not release:
    version = full_version
